### PR TITLE
return new analog reader response

### PR DESCRIPTION
**Pull request by martha-johnston**

### CODE REVIEW

**Review by stuqdog — CHANGES_REQUESTED** [review]
The code generally looks good! a couple small changes requested but that's it.

However, we should probably be forking this off of the `workflows/update-protos` branch rather than `main`, so that all the proto updating happens in a consistent reliable place.

**Comment by martha-johnston** [comment]
> However, we should probably be forking this off of the `workflows/update-protos` branch rather than `main`, so that all the proto updating happens in a consistent reliable place.

sure I'll switch my fork for future PRs

**Comment by stuqdog** [comment]
> > However, we should probably be forking this off of the `workflows/update-protos` branch rather than `main`, so that all the proto updating happens in a consistent reliable place.
> 
> sure I'll switch my fork for future PRs. is there anything I need to do in this one to make sure it's up to date?

We should update so that we're merging into `workflows/update-protos` rather than `main`, then merge this into `update-protos` and merge that into `main`.

**Review by stuqdog — APPROVED** [review]
lgtm (modulo the discussed branch fixes).

**Pull request merged**
