### PR TITLE
[APP-6630] Rebuild iOS Project and Update README to Specify Necessary Versions

### PR DESCRIPTION
**Pull request by bashar-515**
This PR rebuilds the example app and updates the README to note that specific versions of Xcode and Flutter are required for the app to build and run successfully on an iOS emulator.

### CODE REVIEW

**Comment by clintpurser** [comment]
@bashar-515 did you mean to close this?

**Comment by bashar-515** [comment]
@clintpurser @kevin49999 tagged both of you guys as reviewers just in case you wanted to take a look but feel free to take yourself off

**Comment by njooma** [comment]
I don't think these restrictions are required anymore -- can we close @bashar-515 ?

**Comment by bashar-515** [comment]
> I don't think these restrictions are required anymore -- can we close @bashar-515 ?

Sorry I am just now seeing this. I haven't been able to build locally. Am I good to use Xcode 16 and Flutter 3.24?

**Comment by njooma** [comment]
@bashar-515 yes you should be able to. I've been using the latest version of both and everything's been working for me.

**Comment by bashar-515** [comment]
> @bashar-515 yes you should be able to. I've been using the latest version of both and everything's been working for me.

okay lemme fidget w it

**Pull request closed without merging**
